import React, { Component } from "react";
import Head from "next/head";

export default function HeadTag({ title }) {
  return (
    <Head>
      <title>{title} : AllTime</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta property="og:title" content={title} />
      <meta property="og:url" content="https://harin.spacedev.space" />
      <meta property="og:description" content="고등학교 생활의 필수아이템, AllTime" />
      <meta property="og:site_name" value="Powered By Next.js" />
      <meta
        property="og:image"
        content="https://i.ibb.co/SrMqBKQ/logo.png"
      />
    </Head>
  );
}
