import React, { Component } from "react";
import Head from "next/head";

export default function HeadTag({ title }) {
  return (
    <Head>
      <title>{title} : 하린봇</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta property="og:title" content={title} />
      <meta property="og:url" content="https://harin.spacedev.space" />
      <meta property="og:description" content="Harin Bot Web page" />
      <meta property="og:site_name" value="Powered By Next.js" />
      <meta
        property="og:image"
        content="https://cdn.discordapp.com/avatars/893841721958469703/d1d394c5cbe6b81ad4c18b8502f64d07"
      />
    </Head>
  );
}
